name: 'Create Date File and Display PWD'
description: 'Creates a file with the current date and time as the filename and displays pwd'
runs:
  using: 'composite'
  steps:
    - id: get_datetime
      run: |
        datetime=$(date '+%Y-%m-%d_%H-%M-%S')
        echo $datetime > datetime.txt
      shell: bash

    - run: chmod +x entrypoint.sh
      shell: bash
      working-directory: ${{ github.action_path }}

    - run: ./entrypoint.sh
      shell: bash
      working-directory: ${{ github.action_path }}

    - id: set_output
      run: echo "current_datetime=$(cat datetime.txt)" >> $GITHUB_ENV

outputs:
  current_datetime: ${{ env.current_datetime }}
