name: "Create Date and Time File Action"
description: "Creates a file with the current date and time, and sets output variables"
runs:
  using: "composite"
  steps:
    - name: Create datetime file
      id: step1
      shell: bash
      run: |
        datetime=$(date '+%Y-%m-%d_%H-%M-%S')
        echo $datetime > datetime.txt
        echo "datetime=$datetime" >> $GITHUB_OUTPUT
        echo "$GITHUB_OUTPUT"
    
    - name: Create var1 based on datetime
      id: step2
      shell: bash
      run: |
        datetime_var1="First output based on datetime: ${{ steps.step1.outputs.datetime }}"
        echo "var1=$datetime_var1" >> $GITHUB_OUTPUT
        cat "$GITHUB_OUTPUT"

    - name: Create var2 using var1
      id: step3
      shell: bash
      run: |
        datetime_var2="Second output using var1: ${{ steps.step2.outputs.var1 }}"
        echo "var2=$datetime_var2" >> $GITHUB_OUTPUT
        cat "$GITHUB_OUTPUT"

    - name: Create combined var3 using datetime and var2
      id: step4
      shell: bash
      run: |
        combined_var="Combined output using datetime and var2: ${{ steps.step1.outputs.datetime }} & ${{ steps.step3.outputs.var2 }}"
        echo "var3=$combined_var" >> $GITHUB_OUTPUT
        cat "$GITHUB_OUTPUT"

outputs:
  datetime:
    description: "The created datetime"
    value: ${{ steps.step1.outputs.datetime }}
  var1:
    description: "Output based on datetime"
    value: ${{ steps.step2.outputs.var1 }}
  var2:
    description: "Second output using var1"
    value: ${{ steps.step3.outputs.var2 }}
  var3:
    description: "Combined output using datetime and var2"
    value: ${{ steps.step4.outputs.var3 }}
