name: "Create Date File Action"
description: "Creates a file with the current date and time as the filename and sets multiple outputs."
runs:
  using: "composite"
  steps:
    - name: Create datetime file and output datetime
      id: step1
      shell: python
      run: |
        from datetime import datetime
        import os
        
        # Step 1: Create datetime file and set output
        current_datetime = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
        with open(f"{current_datetime}.txt", "w") as f:
            f.write("This is a file created with Python.")
        
        # Set the datetime as output (stored in $GITHUB_OUTPUT)
        print(f"datetime={current_datetime}", file=open(os.environ['GITHUB_OUTPUT'], 'a'))

    - name: Create var1 output
      id: step2
      shell: python
      run: |
        import os
        
        # Retrieve datetime from step1 output
        datetime_value = "${{ steps.step1.outputs.datetime }}"
        
        # Create first variable based on datetime
        var1 = f"First output based on datetime: {datetime_value}"
        
        # Set var1 as output
        print(f"var1={var1}", file=open(os.environ['GITHUB_OUTPUT'], 'a'))

    - name: Create var2 output using var1
      id: step3
      shell: python
      run: |
        import os
        
        # Retrieve var1 from step2 output
        var1_value = "${{ steps.step2.outputs.var1 }}"
        
        # Create second variable using var1
        var2 = f"Second output using var1: {var1_value}"

        # Set var2 as output
        print(f"var2={var2}", file=open(os.environ['GITHUB_OUTPUT'], 'a'))

    - name: Create combined var output using datetime and var2
      id: step4
      shell: python
      run: |
        import os
        
        # Retrieve datetime and var2 from previous steps
        datetime_value = "${{ steps.step1.outputs.datetime }}"
        var2_value = "${{ steps.step3.outputs.var2 }}"
        
        # Create combined variable
        combined_var = f"Combined output using datetime and var2: {datetime_value} & {var2_value}"

        # Set combined_var as output
        print(f"var3={combined_var}", file=open(os.environ['GITHUB_OUTPUT'], 'a'))

outputs:
  datetime:
    description: "Datetime output"
    value: ${{ steps.step1.outputs.datetime }}
  var1:
    description: "Var1 output"
    value: ${{ steps.step2.outputs.var1 }}
  var2:
    description: "Var2 output"
    value: ${{ steps.step3.outputs.var2 }}
  var3:
    description: "Combined output"
    value: ${{ steps.step4.outputs.var3 }}
